library("dplyr")
library("tidyr")
library("ggplot2")
library("ggpattern")

setwd("C:/Users/lwang03/OneDrive - Environmental Protection Agency (EPA)/Profile/Documents/Kansas_Roar")

Data <- read.csv("Soil1_20240520_LW Modified.csv", header = T)
Field_col <- c(E1 = "#543fbf", E2 = "#117733", E3 = "#44AA99", SS1 = "#BB9D05" , S2 = "#CC6677", S3 = "#88CCEE", S4 = "#AA4499" , W1 ="#882255" )
Season_col <- c(Spring = "#56B4E9", Fall = "#E69900")
#Selecting the variables that are connected to the Haney Test and Nitrogen, changing the names
Haney_Test <- Data %>% select(Crop.2023,
                              Tillage,
                              Cover.Crop,
                              Crop_Diversity,
                              Field,
                              Sample_ID,
                              Season,
                              OM.,
                              Ace.Protein.g.Kg,
                              NO3_N_H2O,
                              OC_H2O_ppm,
                              ON_H2O_ppm,
                              CN_H2O,
                              NH4_N_H2O,
                              CO2,
                              N_H2O,
                              X.MAC,
                              Aggstab1_2mm,
                              X..Clay,
                              X..Silt,
                              X..Sand,
                              CEC,
                              ON_release_ppm,
                              Ca_ppm,
                              Mg_ppm,
                              K_ppm,
                              Na_ppm,
                              X.Hsat,
                              X.Ksat,
                              X.Casat,
                              X.Mgsat,
                              X.Nasat,
                              H3A_NO3,
                              H3A_NH4,
                              H3A_P,
                              H3A_IP,
                              H3A_OP,
                              H3A_ICAPS,
                              H3A_ICAPK,
                              H3A_ICAPCa,
                              H3A_ICAPAl,
                              H3A_ICAPFe,
                              H3A_ICAPZn,
                              H3ACu,
                              H3A_ICAPMg,
                              H3A_ICAPNa,
                              SoilHealth,
                              Biomass,
                              Total_Fungi_Biomass,
                              UndifferentiatedBiomass,
                              TotalBacteriabiomass,
                              Fungi_Bacteria,
                              Protozoa_biomasss
) %>% 
  rename(`Organic Matter (%)` = "OM.",
         `Water Extractable Nitrate Nitrogen (mg/kg)` = "NO3_N_H2O",
         `Water Extractable Organic Carbon (mg/kg)` = "OC_H2O_ppm",
         `Water Extractable Organic Nitrogen (mg/kg)` = "ON_H2O_ppm",
         `WEOC:WEON` = "CN_H2O",
         `Calcium (mg/kg)` = "Ca_ppm",
         `Potassium (mg/kg)` = "K_ppm",
         `Magnesium (mg/kg)` = "Mg_ppm",
         `Sodium (mg/kg)` = "Na_ppm",
         `Water Extractable Ammonium Nitrogen (mg/kg)` = "NH4_N_H2O",
         `24 hour CO2 Respiration (mg/kg)` = "CO2",
         `Microbially Active Carbon (%)` = "X.MAC",
         `Autoclavable Citrate Protein (g/kg)` = "Ace.Protein.g.Kg",
         `Organic Nitrogen Release (mg/kg)` = "ON_release_ppm",
         `H3A Extracted Nitrate (mg/kg)` = "H3A_NO3",
         `H3A Extracted Ammonium (mg/kg)` = "H3A_NH4",
         `H3A Extracted Phosphorous (mg/kg)` = "H3A_P",
         `H3A Extracted Inorganic Phosphorous (mg/kg)` = "H3A_IP",
         `H3A Extracted Organic Phosphorous (mg/kg)` = "H3A_OP",
         `H3A Extracted Sulfur (mg/kg)` = "H3A_ICAPS",
         `H3A Extracted Potassium (mg/kg)` = "H3A_ICAPK",
         `Water Extractable Nitrogen (mg/kg)` = "N_H2O",
         `H3A Extracted Calcium (mg/kg)` = "H3A_ICAPCa",
         `H3A Extracted Aluminum (mg/kg)` = "H3A_ICAPAl",
         `H3A Extracted Iron (mg/kg)` = "H3A_ICAPFe",
         `H3A Extracted Zinc (mg/kg)` = "H3A_ICAPZn",
         `H3A Extracted Copper (mg/kg)` = "H3ACu",
         `H3A Extracted Magnesium (mg/kg)` = "H3A_ICAPMg",
         `H3A Extracted Sodium (mg/kg)` = "H3A_ICAPNa",
         `Clay (%)` = "X..Clay",
         `Silt (%)` ="X..Silt",
         `Sand (%)` ="X..Sand",
         `Aggregate Stability 1-2 mm (%)` = "Aggstab1_2mm",
         `Microbial Biomass (ug/g)` = "Biomass",
         `Fungal Biomass (ug/g)` = "Total_Fungi_Biomass",
         `Undifferentiated Biomass (ug/g)` = "UndifferentiatedBiomass",
         `Bacteria Biomass (ug/g)` = "TotalBacteriabiomass",
         `Fungi:Bacteria (ug/g)` = "Fungi_Bacteria",
         `% BS H` = X.Hsat,
         `% BS K` = X.Ksat,
         `% BS Mg` = X.Mgsat,
         `% BS Ca` = X.Casat,
         `% BS Na` = X.Nasat,
         `Protazoa Biomass (ug/g)` = "Protozoa_biomasss"
  ) %>%
  mutate( `Carbon (%)` = `Organic Matter (%)`/1.72) %>%
  filter(`WEOC:WEON` < 80)(

names <- colnames(Haney_Test[,8:length(Haney_Test)])